let name="vignesh";
console.log(name);
let age=20;
let salary=70000.50;
console.log(age);
console.log(salary);
let isStudent=true;
console.log(isStudent);
let x;
console.log(x);
let result=null;
console.log(result);
